[package]
name = "tauri-plugin-mobile-capture"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
links = "tauri-plugin-mobile-capture"
license = "MIT"

[lib]
name = "tauri_plugin_mobile_capture"
crate-type = ["lib"]

[dependencies]
tauri = { version = "2.11.3", default-features = false }

[build-dependencies]
tauri-plugin = { version = "2.5", features = ["build"] }
